# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Casanova' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Casanova
  pod 'Alamofire', '~> 4.4'
  pod 'TagListView', '1.2.0'
  pod 'AliyunOSSiOS', '~> 2.0'
  pod 'NVActivityIndicatorView'
  pod 'Down', '0.3.4'
  pod 'Firebase/Core'
  pod 'IDZSwiftCommonCrypto', '~> 0.9.1'
  pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift3.2'
  pod 'Nuke', '~> 5.0'
  
  # U-Share SDK UI模块（分享面板，建议添加）
  pod 'UMengUShare/UI'
  # 集成微信(精简版0.2M)
  pod 'UMengUShare/Social/ReducedWeChat'
  # 集成邮件
  pod 'UMengUShare/Social/Email'
  # 集成短信
  pod 'UMengUShare/Social/SMS'
end
